### PR TITLE
Update sign-with-akv-cert.md

### PR DESCRIPTION
**Pull request by myevit**

### CODE REVIEW

**Comment by anarvekar-msft** [comment]
I am not seeing the **Key Management Operations** section under Secret Permissions. Could you please fix this or clarify what it is? 
MicrosoftTeams-image

**Comment by myevit** [comment]
sorry typo it's Secret Management Operations.
Without  Secret Management Operations Get, List  and  Certificate Management Operations Get, List enabled VS can't use certificate from Azure to sign apps.

image

**Review by anarvekar-msft — CHANGES_REQUESTED** [review]
Please make the necessary changes to your PR and then I will approve and merge it

**Comment by myevit** [comment]
ok. Done.

**Pull request merged**
