### PR TITLE
Update group-policy-msix.md

### PR DESCRIPTION
**Pull request by yuokochi**
Delete this as it is the duplicate as the table above.

### CODE REVIEW

**Comment by yuokochi** [comment]
@dianmsft @stevewhims @v-alje @DCtheGeek @mcleanbyron @openpublishbuild 
To contributors,
Could you check this commit?
Delete this as it is the duplicate as the table above.

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
We prefer Microsoft folks to contribute to https://github.com/MicrosoftDocs/msix-pr, if possible. :)

-Steve

**Comment by yuokochi** [comment]
@stevewhims Thank you for your support.
If I do nothing and wait will the document be changed?
When will the documentation be released?

**Comment by stevewhims** [comment]
> @stevewhims Thank you for your support. If I do nothing and wait will the document be changed? When will the documentation be released?

I know the workflow for the private repo. For this public repo, I'm afraid I don't know. I can confirm that your changes haven't arrived in the private repo yet (so I'd guess that's why they're not live). Also, since this PR can be seen publicly (because this is a public repo), I don't want to share here the identity of someone who might help. All I can do at this stage is go looking for you internally. If I find you, I'll let you know the identity of the owner of the private repo, who might be able to help.

**Pull request merged**
